<?php

namespace common\widgets;

use yii\base\Widget;

class AboutWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('about');
    }
}
