<?php
/**
 * Created by PhpStorm.
 * User: andrew
 * Date: 09.09.16
 * Time: 11:24
 */

namespace common\widgets;

use yii\base\Widget;
use frontend\models\ContactForm;

class ContactWidget extends Widget
{
    public $model;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->model = new ContactForm();
        if ($this->model->load(\Yii::$app->request->post()) && $this->model->contact()) {

            \Yii::$app->session->setFlash('contactFormSubmitted');

        } else {

            return $this->render('contact', ['model' => $this->model]);
        }
    }

    public function run()
    {
        return $this->render('contact', ['model' => $this->model]);
    }
}
