<?php

namespace common\widgets;

use yii\base\Widget;
use yii\bootstrap\Nav;

class MenuWidget extends Widget
{
    public $model;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render('menu', ['model' => $this->model]);
    }
}